accounts/urls.py
from django.conf.urls import url

from . import views


app_name = 'accounts'
urlpatterns = [
    url(
        regex=r'^logout/$',
        view=views.auth_logout,
        name='logout'
    ),
    url(
        regex=r'^password/change/$',
        view=views.password_change,
        name="password_change"
    ),
    url(
        regex=r'^password/reset/$',
        view=views.password_reset,
        name="password_reset"
    ),
    url(
        regex=r'^password/reset/confirm/'
              r'(?P<uidb64>[0-9A-Za-z_\-]+)/'
              r'(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        view=views.password_reset_confirm,
        name="password_reset_confirm"
    ),
]

api/urls.py
from django.conf.urls import url

from push_notifications.api.rest_framework import APNSDeviceAuthorizedViewSet
from . import views
from .views import APIHomeView
from .views import (AccountCreateAPIView, MyUserDetailAPIView,
                    MyUserListAPIView, PhotoCreateAPIView)
from .views import FeedAPIView
from .views import NotificationAPIView, NotificationAjaxAPIView
from .views import (PasswordChangeView, PasswordResetView,
                    PasswordResetConfirmView)
from .views import (OwnPartyListAPIView, PartyCreateAPIView,
                    PartyDetailAPIView, PartyListAPIView, UserPartyListAPIView)
from .views import SearchListAPIView


urlpatterns = [
    # G E N E R A L
    url(
        regex=r'^$',
        view=APIHomeView.as_view(),
        name='api_home'
    ),
    url(
        regex=r'^search/$',
        view=SearchListAPIView.as_view(),
        name='search_api'
    ),
    url(
        regex=r'^device/apns/$',
        view=APNSDeviceAuthorizedViewSet.as_view({'post': 'create'}),
        name='create_apns_device'
    ),

    # A C C O U N T S
    url(
        regex=r'^accounts/$',
        view=MyUserListAPIView.as_view(),
        name='user_account_list_api'
    ),
    url(
        regex=r'^accounts/create/$',
        view=AccountCreateAPIView.as_view(),
        name='account_create_api'
    ),
    url(
        regex=r'^accounts/(?P<user_pk>\d+)/$',
        view=MyUserDetailAPIView.as_view(),
        name='user_account_detail_api'
    ),
    url(
        regex=r'^accounts/photos/create/$',
        view=PhotoCreateAPIView.as_view({'post': 'create'}),
        name='photo_create_api'
    ),
    url(
        regex=r'^accounts/photos/delete/(?P<photo_pk>\d+)/$',
        view=views.photo_delete_api,
        name='photo_delete_api'
    ),
    url(
        regex=r'^follow/(?P<user_pk>\d+)/$',
        view=views.follow_status_api,
        name='follow_status_api'
    ),
    url(
        regex=r'^privacy_status/(?P<user_pk>\d+)/$',
        view=views.privacy_status_api,
        name='privacy_status_api'
    ),
    url(
        regex=r'^block/(?P<user_pk>\d+)/$',
        view=views.block_user_api,
        name='block_user_api'
    ),

    # A U T H E N T I C A T I O N
    url(
        regex=r'^password/reset/$',
        view=PasswordResetView.as_view(),
        name='rest_password_reset'
    ),
    url(
        regex=r'^password/reset/confirm/'
              r'(?P<uidb64>[0-9A-Za-z_\-]+)/'
              r'(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        view=PasswordResetConfirmView.as_view(),
        name='rest_password_reset_confirm'
    ),

    url(
        regex=r'^password/change/$',
        view=PasswordChangeView.as_view(),
        name='rest_password_change'
    ),

    # F E E D
    url(
        regex=r'^feed/(?P<user_id>\d+)/$',
        view=FeedAPIView.as_view(),
        name='feed_list_api'
    ),

    # F L A G S
    url(
        regex=r'^flag/create/(?P<party_pk>\d+)/$',
        view=views.flag_create_api,
        name='flag_create_api'
    ),

    # N O T I F I C A T I O N S
    url(
        regex=r'^notifications/$',
        view=NotificationAPIView.as_view(),
        name='notification_list_api'
    ),
    url(
        regex=r'^notifications/unread/$',
        view=NotificationAjaxAPIView.as_view(),
        name='get_unread_notifications_api'
    ),

    # P A R T I E S
    url(
        regex=r'^parties/$',
        view=PartyListAPIView.as_view(),
        name='party_list_api'
    ),
    url(
        regex=r'^parties/own/$',
        view=OwnPartyListAPIView.as_view(),
        name='own_party_list_api'
    ),
    url(
        regex=r'^parties/(?P<user_pk>\d+)/$',
        view=UserPartyListAPIView.as_view(),
        name='user_party_list_api'
    ),
    url(
        regex=r'^party/(?P<party_pk>\d+)/$',
        view=PartyDetailAPIView.as_view(),
        name='party_detail_api'
    ),
    url(
        regex=r'^party/create/$',
        view=PartyCreateAPIView.as_view({'post': 'create'}),
        name='party_create_api'
    ),
    url(
        regex=r'^party/attend/(?P<party_pk>\d+)/$',
        view=views.party_attend_api,
        name='party_attend_api'
    ),
    url(
        regex=r'^party/approve/(?P<party_pk>\d+)/(?P<user_pk>\d+)/$',
        view=views.requester_approve_api,
        name='requester_approve_api'
    ),
    url(
        regex=r'^party/deny/(?P<party_pk>\d+)/(?P<user_pk>\d+)/$',
        view=views.requester_deny_api,
        name='requester_deny_api'
    ),
    url(
        regex=r'^party/like/(?P<party_pk>\d+)/$',
        view=views.party_like_api,
        name='party_like_api'
    ),
]

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Pulse</title>
    <meta name="author" content="Pulse">
    <meta name="description" content="Party locator">
    <meta name="keywords" content="party, social, college">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1, minimum-scale=1, maximum-scale=1">
    <meta name="msapplication-tap-highlight" content="no">

    <!-- CSS -->
    <link href="{% static 'vendors/bootstrap/bootstrap.min.css' %}" rel="stylesheet" media="screen">
    <style>
        body {
            background:#292E32;
            color:#fff; }
        .main-section {
            text-align:center;
            margin-top:5%; }
        .pulse-logo {
            width:18%;
            height:18%; }
    </style>
    <style>{% block style %}{% endblock style %}</style>
  </head>

  <body>
    {% spaceless %}
      {% block jumbotron %}{% endblock jumbotron %}
      <div class="container">
        {% if messages %}
          {% for message in messages %}
            <div role="alert" style="text-align: center;" class="alert alert-dismissible
              {% if 'success' in message.tags %}
                  alert-success
              {% elif 'info' in message.tags %}
                  alert-info
              {% elif 'warning' in message.tags %}
                  alert-warning
              {% else %}
                  alert-danger
              {% endif %} col-sm-10 col-sm-offset-1">
              <button id='marketing-message-btn' type="button" class="close" data-dismiss="alert">
                <span aria-hidden="true">&times;</span>
                <span class="sr-only">Close</span>
              </button>
              {% if 'safe' in message.tags %}
                {{ message|safe }}
              {% else %}
                {{ message }}
              {% endif %}
            </div>
          {% endfor %}
        {% endif %}

        {% block content %}{% endblock content %}
      </div>

      <!-- JavaScript -->
      <script src="{% static 'vendors/jQuery/jquery.min.js' %}" type="text/javascript"></script>
      <script src="{% static 'vendors/bootstrap/bootstrap.min.js' %}" type="text/javascript"></script>
      {% block jquery %}{% endblock jquery %}
    {% endspaceless %}
  </body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
  <div class="main-section">
    <h1>Welcome to Pulse!</h1>
    <br/><br/>
    <img class="pulse-logo" src="{% static 'img/pulse-logo.png' %}" alt="Pulse logo" />
  </div>
{% endblock content %}

templates/password_reset_email.html
<!doctype html>
<html>
<head>
<meta name="viewport" content="width=device-width">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Password Reset</title>
<style>
/* -------------------------------------
    GLOBAL
------------------------------------- */
* {
  font-family: "Helvetica Neue", "Helvetica", Helvetica, Arial, sans-serif;
  font-size: 100%;
  line-height: 1.6em;
  margin: 0;
  padding: 0; }
img {
  max-width: 600px;
  width: 100%; }
body {
  -webkit-font-smoothing: antialiased;
  height: 100%;
  -webkit-text-size-adjust: none;
  width: 100% !important; }
/* -------------------------------------
    ELEMENTS
------------------------------------- */
a {
  color: #348eda; }
.btn-primary {
  Margin-bottom: 10px;
  width: auto !important; }
.btn-primary td {
  background-color: #348eda;
  border-radius: 25px;
  font-family: "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
  font-size: 14px;
  text-align: center;
  vertical-align: top; }
.btn-primary td a {
  background-color: #348eda;
  border: solid 1px #348eda;
  border-radius: 25px;
  border-width: 10px 20px;
  display: inline-block;
  color: #ffffff;
  cursor: pointer;
  font-weight: bold;
  line-height: 2;
  text-decoration: none; }
.last {
  margin-bottom: 0; }
.first {
  margin-top: 0; }
.padding {
  padding: 10px 0; }
/* -------------------------------------
    BODY
------------------------------------- */
table.body-wrap {
  padding: 20px;
  width: 100%; }
table.body-wrap .container {
  border: 1px solid #f0f0f0; }
/* -------------------------------------
    FOOTER
------------------------------------- */
table.footer-wrap {
  clear: both !important;
  width: 100%; }
.footer-wrap .container p {
  color: #666666;
  font-size: 12px; }
table.footer-wrap a {
  color: #999999; }
/* -------------------------------------
    TYPOGRAPHY
------------------------------------- */
h1,
h2,
h3 {
  color: #111111;
  font-family: "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
  font-weight: 200;
  line-height: 1.2em;
  margin: 40px 0 10px; }
h1 {
  font-size: 36px; }
h2 {
  font-size: 28px; }
h3 {
  font-size: 22px; }
p,
ul,
ol {
  font-size: 14px;
  font-weight: normal;
  margin-bottom: 10px; }
ul li,
ol li {
  margin-left: 5px;
  list-style-position: inside; }
/* ---------------------------------------------------
    RESPONSIVENESS
------------------------------------------------------ */
/* Set a max-width, and make it display as block so it will automatically stretch to that width, but will also shrink down on a phone or something */
.container {
  clear: both !important;
  display: block !important;
  Margin: 0 auto !important;
  max-width: 600px !important; }
/* Set the padding on the td rather than the div for Outlook compatibility */
.body-wrap .container {
  padding: 20px; }
/* This should also be a block element, so that it will fill 100% of the .container */
.content {
  display: block;
  margin: 0 auto;
  max-width: 600px; }
/* Let's make sure tables in the content area are 100% wide */
.content table {
  width: 100%; }
</style>
</head>

<body bgcolor="#f6f6f6">

<!-- body -->
<table class="body-wrap" bgcolor="#f6f6f6">
  <tr>
    <td></td>
    <td class="container" bgcolor="#FFFFFF">

      <!-- content -->
      <div class="content">
      <table>
        <tr>
          <td>
            <p>Hi,</p>
            <p>We wanted to let you know that your email was entered in the forgotten password form at Pulse.<br/>
            If you made this request, please click the button below to create a new password:</p>
            <h2>Password reset:</h2>
            <!-- button -->
            <table class="btn-primary" cellpadding="0" cellspacing="0" border="0">
              <tr>
                <td>
                  <a href="{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}">
                    RESET PASSWORD
                  </a>
                </td>
              </tr>
            </table>
            <!-- /button -->
            <br/><br/>
            <p>If you forgot, your email is: <b>{{ user.email }}</b></p>
            <p>If you don't think this was you, please ignore this email.</p>
            <p>Thank you!</p>
            <p><a href="{{ protocol }}://{{ domain }}">{{ domain }}</a></p>
          </td>
        </tr>
      </table>
      </div>
      <!-- /content -->
    </td>
    <td></td>
  </tr>
</table>
<!-- /body -->

<!-- footer -->
<table class="footer-wrap">
  <tr>
    <td></td>
    <td class="container">

      <!-- content -->
      <div class="content">
        <table>
          <tr>
            <td align="center">
              <!-- <p>Don't like these annoying emails? <a href="#"><unsubscribe>Unsubscribe</unsubscribe></a>.</p> -->
            </td>
          </tr>
        </table>
      </div>
      <!-- /content -->

    </td>
    <td></td>
  </tr>
</table>
<!-- /footer -->

</body>
</html>

templates/password_set.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block content %}
  <div class="main-section">
    <h1>Reset Password</h1>
    <br/><br/>
    <form action="." method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form|crispy }}
      <input class="btn btn-primary" type="submit" value="Reset Password" />
    </form>
  </div>
{% endblock content %}

templates/share_party.html
{% extends 'base.html' %}

{% block content %}
    <h1 class="text-center"></h1>
{% endblock content %}

{% block jquery %}
    <script type="text/javascript">
        $(document).ready(function() {
            var user_agent_header = navigator.userAgent;
            if(user_agent_header.indexOf('iPhone')!=-1 || user_agent_header.indexOf('iPod')!=-1){
                var url = window.location.href;
                var result = url.replace(/(^\w+:|^)\/\//, '');
                window.location = "PulseSocialAppUrlScheme://" + result;
                setTimeout(function() {
                    window.location.href = 'itms-apps://itunes.apple.com/us/app/pulse-social-app/id1194288589?mt=8';
                }, 300);
            }
            else {
                $('h1').text('Must be on an iPhone or iPod to view.')
            }
        });
    </script>
{% endblock jquery %}

templates/terms_of_use.html
{% extends 'base.html' %}

<style>
    {% block style %}
        .main-section{
            background-color: #fff;
            border-radius: 4px;
            color: #333;
            text-align: left;
            padding: 7px 30px;
            margin-bottom: 50px; }
        ol li {
            font-weight: 700;
            line-height: 2.5; }
        li {
            padding-left: 10px; }
    {% endblock style %}
</style>

{% block content %}
  <div class="main-section">
    <h2>Terms of Usage</h2>
    <br>
    <p>
      By accessing or using the Pulse platform, the Pulse service, or any other applications (including mobile applications) made available by Pulse Enterprises LLC (together, the "Service"), however accessed, you agree to be bound by these terms of use (hereinafter "Terms of Usage"). The Service is owned and controlled by Pulse Enterprises LLC (hereinafter "Pulse"). <b>These Terms affect your legal rights and obligations. If you do not agree to be bound by all of these Terms of Use, do not access or use the Service. Your continued utilization of the Pulse platform, Service, or application will be representative of your agreement to observe and be bound by these Terms of Usage.</b>
    </p>
    <h5 style="font-style:bold;">
      ARBITRATION NOTICE: YOU AGREE THAT DISPUTES BETWEEN YOU AND PULSE WILL BE RESOLVED BY BINDING, INDIVIDUAL ARBITRATION AND YOU WAIVE YOUR RIGHT TO PARTICIPATE IN A CLASS ACTION LAWSUIT OR CLASS-WIDE ARBITRATION.
    </h5>
    <ol>
      <li>You must be 18 years old to access or use the Service.</li>
      <li>You agree that you access or use the Service at your own risk.</li>
      <li>You agree that due to the nature of the utility of Pulse, you may be physically harmed while engaging in any event viewed and or attended on or through Pulse. Should such happen, you agree that since Pulse is merely a connector between you and the host of the said event, you hereby agree that Pulse shall not in any way, shape, or form be held liable for such damages resulting from the said physical harm to your person.</li>
      <li>You agree that you will not hold Pulse liable should any damages of any kind occur as a result of your use of the Service.</li>
      <li>You may not create falsified, fraudulent, or fabricated event postings on Pulse.</li>
      <li>By using the Service, you agree that you may be subjected to a high level of risk of physical, emotional, and or monetary damages that may result from the actions of others users, either through the Service, or outside of the Service. You agree that in the event that you do incur such damages, you shall defend and hold harmless Pulse in any legal action.</li>
      <li>Pulse does not in any way, shape, or form, condone the consumption of alcoholic beverages by those who have yet to attain the age of 21. Furthermore, Pulse advocates and strictly requires that in the course of utilizing the Service, you observe and obey applicable federal, state, and local laws in effect at the time of your use of the Service. You agree that ANY infraction of this policy, or any applicable federal, state, and local laws will be caused by you and solely you.</li>
      <li>If hosting an event at a residence, you agree not to illegally commercialize the said residence, or you agree to first secure consent in proceeding to do so from your state and or local governing body prior to hosting such.</li>
      <li>By hosting an event through Pulse, you agree to behave responsibly, in accordance with all federal, state, and local laws, mandates, and ordinances. Furthermore, you agree that should any damages, of any kind, occur as a direct or indirect result of your event hosting, you, the person who freely chose to host the event shall be held liable, and not Pulse.</li>
      <li>If you choose to host a commercial event through Pulse, you agree that you and not Pulse shall incur the tax liability associated with revenues generated from the said event.</li>
      <li>You agree not to solicit, abuse, or harass other users that you interact with on the Service.</li>
      <li>Pulse reserves the right to modify these Terms of Usage at any time, with or without notice to You, the user.</li>
    </ol>
  </div>
{% endblock content %}